default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PG_HOST'] %>
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: "doc-mate-developmemt"

test:
  <<: *default
  database: "doc-mate-test"

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  host: <%= ENV["PGHOST"] %>
  database: <%= ENV["PGDATABASE"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  port: <%= ENV["PGPORT"] %>
