---
plan_slug: standard-2
triggers:
- event: branch
  branch_name: main
- event: pull_request
commands:
- checkout
- neetoci-service start postgres 11
- neetoci-version ruby 2.6.5
- cache restore
- bundle install --deployment --path vendor/bundle
- cache store
- bundle exec rake db:setup
- bundle exec rspec
